version: '3.8'

services:
  web:
    build:
      context: ../../Downloads
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - configs/conf.env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - configs/conf.env
    ports:
      - 5432:5432
